# Generated by Django 6.0.3 on 2026-05-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_objetorelacional'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetorelacional',
            name='dados_extras',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
